**

!build.zig

!release
!release/VERSION
!release/docker
!release/docker/render
!release/docker/render/Dockerfile
!release/docker/render/Dockerfile.dockerignore
!release/docker/render/docker-entrypoint.sh

!editor
!editor/tree-sitter-ss
!editor/tree-sitter-ss/src
!editor/tree-sitter-ss/src/**
!editor/tree-sitter-ss/queries
!editor/tree-sitter-ss/queries/highlights.scm

!scripts
!scripts/setup-md4c.sh

!src
!src/**

!stdlib
!stdlib/**
