import std:themes/default

document
pagenos()
end

page title
cover("Hello, ss", "Write slides as programs.", "generated by ss")
end

page body
let title = head("Why ss?")
let body = text <<
- Repeated components are ordinary definitions.
- Page numbers and tables of contents stay in the source.
- Layout can be constrained when needed.
- Math is rendered with real local LaTeX.
>>

~ body.top == title.bottom - 32
end
